---
- name: Ensure Virtual Network Exists
  azure_rm_virtualnetwork:
    name: "{{ az_virtual_network_name }}"
    resource_group: "{{ az_resource_group_name }}"
    state: "present"
    address_prefixes_cidr: "{{ az_virtual_network_address_prefixes_cidr }}"
    tenant: "{{ azure_tenant_id }}"
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    tags: "{{ az_tags_dict }}"
...
